test-src/Data/List.purs

Fix the indentation and use `toList` for the `Arbitrary (List a)` instance.

Update test-src to 0.7

---

src/Data/List.purs
src/Data/List/Lazy.purs

The following behavior of the range function seems inconsistent to me (it *is* inconsistent with `Data.Array.range`)
```purescript
0 .. 2 == 0 : 1 : 2 : Nil
0 .. 1 == 0 : 1 : Nil
0 .. 0 == Nil -- would expect this to be 0 : Nil
```
The appended fix modifies the behavior of `range` to return `singleton 0` in the last case.

Fix inconsistent behavior of range function

---

src/Data/List.purs
src/Data/List/Lazy.purs
src/Data/List/Unsafe.js
src/Data/List/Unsafe.purs
src/Data/List/ZipList.purs
test/Test/Data/List.purs
test/Test/Data/List/Lazy.purs
test/Test/Data/List/Unsafe.purs
test/Test/Main.purs

`unsafeThrow` is a bit dodgy, but getting meaningful errors from unsafe failures may be worthwhile? I think we do that in the unsafe FFI in some other places.

Fix shadow and pattern warnings

---

src/Data/List.purs
test/Test/Data/List.purs

I've noticed, that some of the functions which certainly can be tail recursive aren't, so I've fixed the most obvious. But before going further I thought it would be wise to ask if there is some reason why they weren't tail recursive before?

Make functions in Data.List stack-safe

---

docs/Data/List.md
src/Data/List.purs

Made `init`, `zipWith`, `eq`, `compare` and `map` stack safe

Optimizations

---

docs/Data/List.md
docs/Data/List/Lazy.md
src/Data/List.purs
src/Data/List/Lazy.purs
test/Test/Data/List.purs
test/Test/Data/List/Lazy.purs

The whitespace changes were automatically done by my editor. If the commit has to be cleaner, I can rewrite it.

Update nub / nubBy documentation and unit test to consider element order

---

docs/Data/List.md
docs/Data/List/Lazy.md
src/Data/List.purs
src/Data/List/Lazy.purs

Fixes https://github.com/purescript/purescript-lists/issues/48

Import Data.Unfoldable explicitly to avoid name collision

---

src/Data/List.purs
test/Test/Data/List.purs

The `unfoldableList` implementation wasn't tail-recursive, which caused the problems described here:
https://github.com/hdgarrood/purescript-sequences/issues/20
This pull request changes `unfoldr` so that it is tail-recursive. The provided test fails without the change.

Make unfoldr stack-safe.

---

docs/Data/List.md
docs/Data/List/Lazy.md
docs/Data/List/ZipList.md
src/Data/List.purs
src/Data/List/Lazy.purs
test/Test/Data/List.purs
test/Test/Data/List/Lazy.purs
test/Test/Data/List/Unsafe.purs

Improve names for toList, fromList.

---

LICENSE-GHC.md
README.md
docs/Data/List.md
docs/Data/List/Lazy.md
src/Data/List.purs
src/Data/List/Lazy.purs
test/Test/Data/List.purs
test/Test/Data/List/Lazy.purs
test/Test/Data/List/ZipList.purs
test/Test/Main.purs

I've included GHC's license, as that's what this code is based on.

Transpose (attempt 2)

---

src/Data/List.purs

It was talking about arrays, rather than lists.

Fix comment for snoc function.

---

src/Data/List.purs

It seems the compiler as of the current master (4852b5d) is no longer able to bind operators as function arguments. If this is intentional, should it be listed in https://github.com/purescript/purescript/issues/2012?

Avoid using operators for binding arguments

---

bower.json
src/Data/List.purs

Resolves #40 
Will probably fail to build because the new generics requires psc 0.9.

Add Generic instance

---

src/Data/List/ZipList.purs

Add `Fail` instance for `Bind ZipList`

---

src/Data/List.purs

- Use the infix operator instead of the `Cons` constructor to clean up the code, especially because it remove a lot of parenthesis.
- Modify the `Show` instance to use the infix operator instead of `Cons`:
``` purs
> show (1 : 2 : 3 : Nil)
"(1 : (2 : (3 : Nil)))"
```
Personally, I like this better than
``` purs
"(Cons 1 (Cons 2 (Cons 3 Nil)))"
```
Maybe it would even close #43.

Use colon operator instead of Cons

---

bower.json
src/Data/List.purs
src/Data/List/Lazy.purs
src/Data/List/ZipList.purs
test/Test/Data/List.purs
test/Test/Data/List/Lazy.purs

Blocked by `generics`, and we should probably merge some of the open PRs first too. 
Resolves #75

Updates for 2.0

---

src/Data/List/Lazy.purs
test/Test/Data/List/Lazy.purs

Nearly made a stupid mistake there... deleted the v3 release immediately after tagging it, so will re-release as that once this is in.

Use NonEmptyList for lazy version of group functions

---

src/Data/List/Types.purs
test/Test/Data/List.purs

I haven't implemented this for lazy lists, since it was still causing a stack overflow, and I couldn't figure out why.

Safe traverse, fix #86

---

src/Data/List/Types.purs
test/Test/Data/List.purs

Re-implement `append` in terms of `foldr` to avoid
"RangeError: Maximum call stack size exceeded" errors.
Add tests for functionality and stack-safety.

Make `append` stack-safe

---

src/Data/List/Lazy.purs
src/Data/List/Lazy/Types.purs
test/Test/Data/List/Lazy.purs

Fixes issue #91.
Also made `unfoldr` and `toList` slightly lazier.

Fixing several stack-unsafe functions in Data.List.Lazy

---

src/Data/List/Lazy/NonEmpty.purs
src/Data/List/NonEmpty.purs

For both strict and lazy nonempty lists, a function
appendList :: NonEmptyList ~> List ~> NonEmptyList
(a very handy function for creating an Arbitrary instance for NonEmptyLists).

appendList function for nonempty lists

---

src/Data/List.purs

For consistency with `purescript-arrays`. Or we could do it the other way around? I don't have a strong preference for the ordering, but figured if I was doing it in Haskell I'd produce a list of tuples with the index first.

[BREAKING] Swap arguments to function in `mapWithIndex`

---

test/Test/Data/List/Lazy.purs

Fixes a warning that is issued during compilation of tests.

fix shadowed `xs` warning

---

src/Data/List/Lazy.purs

add some and many for Lazy List

---

src/Data/List.purs

Reversing twice means we rebuild the entire list twice.  Also `O(2n) = O(n)`.

Reimplement snoc with foldr

---

bower.json
src/Data/List/NonEmpty.purs
test/Test/Data/List/NonEmpty.purs
test/Test/Main.purs

Adds the two sorting functions to `NonEmptyList`.

sorting for NonEmptyList

---

src/Data/List/Lazy.purs
test/Test/Data/List/Lazy.purs

addresses #111
This looks a bit different from the signature discussed in that issue, but my inclination is that this is what we are actually looking for. Happy to discuss better ways if anyone can think of one, though.

foldr': lazy right folds

---

package.json
src/Data/List.purs
test/Test/Data/List.purs

https://github.com/purescript-contrib/purescript-parsing/pull/62#discussion_r119991248

add stripPrefix and Pattern for Data.List

---

src/Data/List/NonEmpty.purs

Add cons, snoc, unsnoc

---

src/Data/List/Lazy.purs
test/Test/Data/List/Lazy.purs

https://github.com/purescript-contrib/purescript-parsing/pull/62#discussion_r124173982

define stripPrefix for List.Lazy

---

bower.json

foldable-traversable@3.3.0 is the first release that includes `Traversable1` et al. that was added to this library in a recent release, so we need to make sure that at least that version is required. (None of the dependencies require more than ^3.0.0.)

Require foldable-traversable ^3.3.0

---

src/Data/List.purs
test/Test/Data/List.purs

Similar to the https://github.com/purescript/purescript-arrays/issues/113

Add dropEnd and takeEnd

---

src/Data/List.purs
test/Test/Data/List.purs

Calling `takeEnd` with an `Int` value greater than the length of the list currently leads to an infinite loop. I added a couple test cases to demonstrate this and added a guard in `drop` against negative Ints.

Avoid infinite loop possibility with takeEnd

---

src/Data/List/Lazy.purs
test/Test/Data/List/Lazy.purs

Don't force more than necessary in Data.List.Lazy take

---

bower.json
src/Data/List/Types.purs

Depends on https://github.com/purescript/purescript-nonempty/pull/27
Will update `bower.json` if that gets merged.

NonEmptyList: newtype derive Foldable1

---

bench/Bench/Data/List.purs
bench/Main.purs
bower.json
package.json
src/Data/List/Types.purs
test/Test/Data/List.purs

This is @matthewleon's faster `List.map`, from #135, updated for 0.12.

fast functor updated

---

src/Data/List.purs
src/Data/List/Lazy.purs
src/Data/List/NonEmpty.purs

Related to https://github.com/purescript/purescript-foldable-traversable/pull/111

Change foldM type signature to more closely match foldl

---

src/Data/List.purs
src/Data/List/NonEmpty.purs
test/Test/Data/List.purs
test/Test/Data/List/NonEmpty.purs

Data.List and Data.List.NonEmpty export a group' function so if we rename Data.Array.group' in https://github.com/purescript/purescript-arrays/pull/194 we should also do it there for consistency.

Rename group' to groupAll and add groupAllBy

---

bench/Bench/Data/List.purs
src/Data/List/Types.purs

Performance is improved by using an inlined reverse function, rather than leveraging `foldl`.
Both versions appear to be identical, so it's a bit of a bummer that the concise version is so much slower.
There's a moderate speedup for all list sizes, but it's most significant on large lists. Here are the benchmarking results:
Before:
```
foldr: list (0 elems)
mean   = 1.52 μs
stddev = 416.18 ns
min    = 1.22 μs
max    = 11.11 μs
---
foldr: list (1 elems)
mean   = 2.90 μs
stddev = 22.78 μs
min    = 977.00 ns
max    = 631.81 μs
---
foldr: list (10 elems)
mean   = 5.96 μs
stddev = 21.03 μs
min    = 2.00 μs
max    = 563.57 μs
---
foldr: list (100 elems)
mean   = 16.16 μs
stddev = 50.97 μs
min    = 10.32 μs
max    = 1.54 ms
---
foldr: list (1000 elems)
mean   = 126.53 μs
stddev = 77.85 μs
min …
```

Improve foldr performance ~4x on large lists

---

src/Data/List/Lazy.purs
test/Test/Data/List/Lazy.purs

The previously-named scanrLazy was actually folding to the left. I've
renamed the function and fixed the argument ordering for the folding
function.
Fixes #159

Rename scanrLazy to scanlLazy and fix arg order

---

CHANGELOG.md
src/Data/List/Lazy/Types.purs
src/Data/List/Types.purs

Adds `Eq1` and `Ord1` instances to `NonEmptyList` and `LazyNonEmptyList`
Fixes #186
---
**Checklist:**

Add Eq1 Ord1 to NonEmptyList LazyNonEmptyList

---

CHANGELOG.md

This is a summary of all the commits since the most recent release (v5.4.1).

Add changelog entries since v5.4.1

---

CHANGELOG.md
src/Data/List/Lazy/Types.purs

This pull request changes the output of show for Data.List.Lazy.Types.List and Data.List.Lazy.Types.NonEmptyList from this:
```purs
> Data.List.Lazy.fromFoldable [0, 1]
fromStrict ((Cons 0 (Cons 1 Nil)))
> Data.List.Lazy.NonEmpty.fromFoldable [0, 1]
(Just (NonEmptyList (defer \_ -> (NonEmpty 0 fromStrict ((Cons 1 Nil))))))
```
to that:
```purs
> Data.List.Lazy.fromFoldable [0, 1]
(defer \_ -> 0 : (defer \_ -> 1 : (defer \_ -> Nil)))
> Data.List.Lazy.NonEmpty.fromFoldable [0, 1]
(Just (NonEmptyList (defer \_ -> (NonEmpty 0 (defer \_ -> 1 : (defer \_ -> Nil))))))
```
Alternatively, we could show `(fromFoldable […])` but this makes the output of show less similar:
```purs
> Data.List.Lazy.fromFoldable [0, 1]
(fromFoldable [1,0])
> Data.List.Lazy.NonEmpty.fromFoldable [0, 1]
(Just …
```

Idiomatic Show instance for lazy lists

---

CHANGELOG.md
src/Data/List.purs
src/Data/List/Lazy.purs
src/Data/List/Lazy/NonEmpty.purs
src/Data/List/Lazy/Types.purs
src/Data/List/NonEmpty.purs
src/Data/List/Partial.purs
src/Data/List/Types.purs

Self-explanatory.
Backlinking to purescript/purescript#4071
---
**Checklist:**

Fix warnings revealed by v0.14.1 PS release

---

CHANGELOG.md
src/Data/List/Lazy/NonEmpty.purs

See https://github.com/purescript/purescript/pull/4241. In preparation for `v0.15.x`, fixes the ad-hoc case expression usage.
---
**Checklist:**

Fix ad-hoc usage of case expression

---

.github/workflows/ci.yml
CHANGELOG.md
bower.json
package.json
test/Test/Data/List/NonEmpty.purs

Backlinking to purescript/purescript#4244
Updates project to compile on v0.15.0 PureScript.
---
**Checklist:**

Update to v0.15.0

---

CHANGELOG.md
src/Data/List.purs
src/Data/List/NonEmpty.purs
test/Test/Data/List.purs
test/Test/Data/List/NonEmpty.purs

Fixes #189
Also modified the tests and examples to demonstrate which grouping functions involve sorting.
One of the commits reverts demoing the convenience of the `:||` infix operator proposed in #190. We can redo those changes if that operator is accepted.
---
**Checklist:**

Revise groupAllBy to just use an Ordering function
